ambulatorio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, \
     password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^paciente/', include('apps.paciente.urls', namespace="paciente")),
    url(r'^medico/', include('apps.medico.urls', namespace="medico")),
    url(r'^medicamento/', include('apps.medicamento.urls', namespace="medicamento")),
    url(r'^consulta/', include('apps.consulta.urls', namespace="consulta")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/$', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^reset/password_reset/$', password_reset, 
        {'template_name':'registration/password_reset_form.html', 
        'email_template_name': 'registration/password_reset_email.html'}, name = 'password_reset'),
    url(r'^reset/password_reset_done/$', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name':'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done$', password_reset_complete, 
        {'template_name':'registration/password_reset_complete.html'}, name='password_reset_complete'),
]

apps/consulta/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.consulta.views import index_consulta, consulta_view, consulta_list, consulta_edit, \
	consulta_delete, ConsultaList, ConsultaCreate, ConsultaUpdate, ConsultaDelete

urlpatterns = [
	url(r'^$', login_required(index_consulta)),
	url(r'^registrar/$', login_required(ConsultaCreate.as_view()), name="consulta_registrar"),
	url(r'^listar/$', login_required(ConsultaList.as_view()), name="consulta_listar"),
	url(r'^editar/(?P<pk>\d+)/$', login_required(ConsultaUpdate.as_view()), name="consulta_editar"),
	url(r'^eliminar/(?P<pk>\d+)/$', login_required(ConsultaDelete.as_view()), name="consulta_eliminar"),
]

apps/consulta/models.py
from django.db import models
from apps.paciente.models import Paciente
from apps.medico.models import Medico

# Create your models here.

class Consulta(models.Model):
	paciente = models.ForeignKey(Paciente, null=True, blank=True, on_delete=models.CASCADE)
	fecha_consulta = models.DateField()
	hora_consulta = models.TimeField()
	medico_asignado = models.ForeignKey(Medico, null=True, blank=True, on_delete=models.CASCADE)
	
	def __str__(self):
		return '{} {}'.format(self.paciente.nombres, self.paciente.apellidos)

apps/consulta/forms.py
from django import forms
from apps.consulta.models import Consulta
from django.contrib.admin import widgets

class ConsultaForm(forms.ModelForm):

	class Meta:
		model = Consulta

		fields = [
			'paciente',
			'fecha_consulta',
			'hora_consulta',
			'medico_asignado',
			]

		labels = {
			'paciente': 'Paciente',
			'fecha_consulta': 'Fecha de la Consulta (DD-MM-YYYY)',
			'hora_consulta': 'Hora de la Consulta (HH:MM)',
			'medico_asignado': 'Medico asignado para la Consulta',
		}

		widgets = {
			'paciente': forms.Select(attrs={'class':'form-control'}),
			'fecha_consulta': forms.TextInput(attrs={'class':'form-control'}),
			'hora_consulta': forms.TextInput(attrs={'class':'form-control'}),
			'medico_asignado': forms.Select(attrs={'class':'form-control'}),
		}

apps/consulta/views.py
from django.shortcuts import render, redirect	
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from apps.consulta.forms import ConsultaForm
from apps.consulta.models import Consulta
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

# Create your views here.

def index_consulta(request):
	return HttpResponse("Esta es la vista para la aplicacion Consulta")

def consulta_view(request):
	if request.method == 'POST':
		form = ConsultaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('consulta:consulta_listar')
	else:
		form = ConsultaForm()
	return render(request, 'consulta/consulta_form.html', {'form': form})

def consulta_list(request):
	consulta = Consulta.objects.all().order_by('id')
	contexto = {'consultas': consulta}
	return render(request, 'consulta/consulta_list.html', contexto)

def consulta_edit(request, id_consulta):
	consulta = Consulta.objects.get(id=id_consulta)
	if request.method == 'GET':
		form = ConsultaForm(instance=consulta)
	else:
		form = ConsultaForm(request.POST, instance=consulta)
		if form.is_valid():
			form.save()
		return redirect('consulta:consulta_listar')
	return render(request, 'consulta/consulta_form.html', {'form': form})

def consulta_delete(request, id_consulta):
	consulta = Consulta.objects.get(id=id_consulta)
	if request.method == 'POST':
		consulta.delete()
		return redirect('consulta:consulta_listar')
	return render(request, 'consulta/consulta_delete.html', {'consulta': consulta})

class ConsultaList(ListView):
	model = Consulta
	template_name = 'consulta/consulta_list.html'
	#paginate_by = 5

class ConsultaCreate(CreateView):
	model = Consulta
	form_class = ConsultaForm
	template_name = 'consulta/consulta_form.html'
	succes_url = reverse_lazy('consulta:consulta_listar')

class ConsultaUpdate(UpdateView):
	model = Consulta
	form_class = ConsultaForm
	template_name = 'consulta/consulta_form.html'
	succes_url = reverse_lazy('consulta:consulta_listar')

class ConsultaDelete(DeleteView):
	model = Consulta
	template_name = 'consulta/consulta_delete.html'
	succes_url = reverse_lazy('consulta:consulta_listar')

templates/consulta/consulta_delete.html
{% extends 'base/base.html' %}

{% block title %}

Eliminar Consulta

{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar la consulta de {{ consulta.paciente.nombres }} {{ consulta.paciente.apellidos }} cedula {{ consulta.paciente.cedula }}</h3>
	<button class="btn btn-danger" type="submit"> Sí, eliminar </button>
	<a class="btn btn-default" href="{% url 'consulta:consulta_listar' %}"> Cancelar </a>
</form>

{% endblock %}

templates/consulta/consulta_form.html
{% extends 'base/base.html' %}

{% block title %} 

Registrar Consulta

{% endblock %}

{% block content %}

<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit"> Guardar </button>
</form>

{% endblock %}

templates/consulta/consulta_list.html
{% extends 'base/base.html' %}

{% block title %}

Lista de Consultas

{% endblock %}

{% block content %}

{% if object_list %}
<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Paciente</td>
			<td>Fecha de Consulta</td>
			<td>Hora de Consulta</td>
			<td>Medico Asignado</td>
			<td>Opciones</td>
		</tr>
	</thead>
	<tbody>
	{% if object_list %}
	{% for consulta in object_list %}
		<tr>
			<td>{{ consulta.id }}</td>
			<td>{{ consulta.paciente.nombres }} {{ consulta.paciente.apellidos }}</td>
			<td>{{ consulta.fecha_consulta }}</td>
			<td>{{ consulta.hora_consulta }}</td>
			<td>{{ consulta.medico_asignado.nombre }} {{ consulta.medico_asignado.apellido }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'consulta:consulta_editar' consulta.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'consulta:consulta_eliminar' consulta.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
{% else %}
	<h1>No hay registros de Consultas</h1>
		
{% endif %}
	</tbody>
{% endif %}
</table>

{% endblock %}