ambulatorio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, \
     password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^paciente/', include('apps.paciente.urls', namespace="paciente")),
    url(r'^medico/', include('apps.medico.urls', namespace="medico")),
    url(r'^medicamento/', include('apps.medicamento.urls', namespace="medicamento")),
    url(r'^consulta/', include('apps.consulta.urls', namespace="consulta")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/$', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^reset/password_reset/$', password_reset, 
        {'template_name':'registration/password_reset_form.html', 
        'email_template_name': 'registration/password_reset_email.html'}, name = 'password_reset'),
    url(r'^reset/password_reset_done/$', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name':'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done$', password_reset_complete, 
        {'template_name':'registration/password_reset_complete.html'}, name='password_reset_complete'),
]

apps/consulta/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.consulta.views import index_consulta, consulta_view, consulta_list, consulta_edit, \
	consulta_delete, ConsultaList, ConsultaCreate, ConsultaUpdate, ConsultaDelete

urlpatterns = [
	url(r'^$', login_required(index_consulta)),
	url(r'^registrar/$', login_required(ConsultaCreate.as_view()), name="consulta_registrar"),
	url(r'^listar/$', login_required(ConsultaList.as_view()), name="consulta_listar"),
	url(r'^editar/(?P<pk>\d+)/$', login_required(ConsultaUpdate.as_view()), name="consulta_editar"),
	url(r'^eliminar/(?P<pk>\d+)/$', login_required(ConsultaDelete.as_view()), name="consulta_eliminar"),
]

apps/medicamento/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.medicamento.views import index_medicamento, medicamento_view, medicamento_list, \
	medicamento_edit, medicamento_delete, MedicamentoList, MedicamentoCreate, MedicamentoUpdate, \
	MedicamentoDelete

urlpatterns = [
	url(r'^$', login_required(index_medicamento)),
	url(r'^registrar/$', login_required(MedicamentoCreate.as_view()), name='medicamento_registrar'),
	url(r'^listar/$', login_required(MedicamentoList.as_view()), name='medicamento_listar'),
	url(r'^editar/(?P<pk>\d+)/$', login_required(MedicamentoUpdate.as_view()), name='medicamento_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$', login_required(MedicamentoDelete.as_view()), name='medicamento_eliminar'),
]

apps/medico/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.medico.views import index_medico, medico_view, medico_list, medico_edit, medico_delete, \
	MedicoList, MedicoCreate, MedicoUpdate, MedicoDelete

urlpatterns = [
	url(r'^$', login_required(index_medico), name='index_medico'),
	url(r'^registrar/$', login_required(MedicoCreate.as_view()), name='medico_registrar'),
	url(r'^listar/$', login_required(MedicoList.as_view()), name='medico_listar'),
	url(r'^editar/(?P<pk>\d+)/$', login_required(MedicoUpdate.as_view()), name='medico_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$', login_required(MedicoDelete.as_view()), name='medico_eliminar'),
]

apps/paciente/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.paciente.views import index_paciente, paciente_view, area_view, paciente_list, \
	area_list, paciente_edit, area_edit, paciente_delete, area_delete, PacienteList, AreaList, \
    PacienteCreate, AreaCreate, PacienteUpdate, AreaUpdate, PacienteDelete

urlpatterns = [
    url(r'^$', login_required(index_paciente), name='index_paciente'),
    url(r'^registrar_paciente/$', login_required(PacienteCreate.as_view()), name='paciente_registrar'),
    url(r'^registrar_area/$', login_required(AreaCreate.as_view()), name='area_registrar'),
    url(r'^listar_pacientes/$', login_required(PacienteList.as_view()), name='paciente_listar'),
    url(r'^listar_areas/$', login_required(AreaList.as_view()), name='area_listar'),
    url(r'^editar_paciente/(?P<pk>\d+)/$', login_required(PacienteUpdate.as_view()), name='paciente_editar'),
    url(r'^editar_area/(?P<pk>\d+)/$', login_required(AreaUpdate.as_view()), name='area_editar'),
    url(r'^eliminar_paciente/(?P<pk>\d+)/$', login_required(PacienteDelete.as_view()), name='paciente_eliminar'),
    url(r'^eliminar_area/(?P<id_area>\d+)/$', login_required(area_delete), name='area_eliminar'),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">

  {% block extrastatic %}
  {% endblock %}

  <link rel="stylesheet" href="{% static 'css/bootstrap.min3.css' %}">
  <title>{% block title %} Ambulatorio Karin {% endblock %} </title>
</head>
<body>
<div class="container">

  {% block navbar %}
    <div class="bs-docs-section clearfix">
        <div class="row">
            <div class="col-lg-12">
                <div class="bs-component">
                  <nav class="navbar navbar-default">
                      <div class="container-fluid">
                          <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'paciente:index_paciente' %}">Home</a>
                          </div>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                          <ul class="nav navbar-nav">
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pacientes <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                  <li><a href="{% url 'paciente:paciente_registrar' %}">Registrar</a></li>
                                  <li><a href="{% url 'paciente:paciente_listar' %}">Listar</a></li>
                                </ul>
                              </li>
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Médicos<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'medico:medico_registrar' %}">Registrar</a></li>
                                    <li><a href="{% url 'medico:medico_listar' %}">Listar </a></li>
                                </ul>
                              </li>
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Áreas<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                  <li><a href="{% url 'paciente:area_registrar' %}">Registrar</a></li>
                                  <li><a href="{% url 'paciente:area_listar' %}">Listar</a></li>
                                </ul>
                              </li>
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Medicamentos <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                  <li><a href="{% url 'medicamento:medicamento_registrar' %}">Registrar</a></li>
                                  <li><a href="{% url 'medicamento:medicamento_listar' %}">Listar</a></li>
                                </ul>
                              </li>
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Consultas <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                  <li><a href="{% url 'consulta:consulta_registrar' %}">Registrar</a></li>
                                  <li><a href="{% url 'consulta:consulta_listar' %}">Listar</a></li>
                                </ul>
                              </li>
                          </ul>
                          <ul class="nav navbar-nav navbar-right">
                              <li class="dropdown"><a href="http://www.google.co.ve" onclick="pageTracker._link(this.href); return false;">Ambulatorio Karin</a>
                              </li>
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'logout' %}">Salir</a></li>
                                </ul>
                              </li>
                          </ul>
                        </div>
                    </div>
                </nav>
            </div>
            </div>
        </div>
    </div>    

  {% endblock %}


   {% block content %}
   <h5>Este es el bloque content base</h5>
   {% endblock %}

   {% block footer %}
   {% endblock %}

</div>
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  {% block extrajs %}
  {% endblock %}		
	
</body>
</html>