ambulatorio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, \
     password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^paciente/', include('apps.paciente.urls', namespace="paciente")),
    url(r'^medico/', include('apps.medico.urls', namespace="medico")),
    url(r'^medicamento/', include('apps.medicamento.urls', namespace="medicamento")),
    url(r'^consulta/', include('apps.consulta.urls', namespace="consulta")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/$', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^reset/password_reset/$', password_reset, 
        {'template_name':'registration/password_reset_form.html', 
        'email_template_name': 'registration/password_reset_email.html'}, name = 'password_reset'),
    url(r'^reset/password_reset_done/$', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name':'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done$', password_reset_complete, 
        {'template_name':'registration/password_reset_complete.html'}, name='password_reset_complete'),
]

apps/paciente/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.paciente.views import index_paciente, paciente_view, area_view, paciente_list, \
	area_list, paciente_edit, area_edit, paciente_delete, area_delete, PacienteList, AreaList, \
    PacienteCreate, AreaCreate, PacienteUpdate, AreaUpdate, PacienteDelete

urlpatterns = [
    url(r'^$', login_required(index_paciente), name='index_paciente'),
    url(r'^registrar_paciente/$', login_required(PacienteCreate.as_view()), name='paciente_registrar'),
    url(r'^registrar_area/$', login_required(AreaCreate.as_view()), name='area_registrar'),
    url(r'^listar_pacientes/$', login_required(PacienteList.as_view()), name='paciente_listar'),
    url(r'^listar_areas/$', login_required(AreaList.as_view()), name='area_listar'),
    url(r'^editar_paciente/(?P<pk>\d+)/$', login_required(PacienteUpdate.as_view()), name='paciente_editar'),
    url(r'^editar_area/(?P<pk>\d+)/$', login_required(AreaUpdate.as_view()), name='area_editar'),
    url(r'^eliminar_paciente/(?P<pk>\d+)/$', login_required(PacienteDelete.as_view()), name='paciente_eliminar'),
    url(r'^eliminar_area/(?P<id_area>\d+)/$', login_required(area_delete), name='area_eliminar'),
]

apps/paciente/models.py
from django.db import models
# Create your models here.

class Area(models.Model):
	nombre = models.CharField(max_length=20)
	ubicacion = models.CharField(max_length=20)
	jefe = models.CharField(max_length=20)

	def __str__(self):
		return self.nombre

class Paciente(models.Model):
	GENEROS = (
		('F', 'Femenino'),
		('M', 'Masculino'),
		('I', 'Indefinido')
	)

	FUMA = (
		('S', 'Si'),
		('N', 'No'),
	)
	nombres = models.CharField(max_length=60)
	apellidos = models.CharField(max_length=60)
	cedula = models.CharField(max_length=8)
	fecha_nacimiento = models.DateField()
	edad = models.IntegerField()
	genero = models.CharField(max_length=1, choices=GENEROS)
	tipo_sangre = models.CharField(max_length=5)
	telefono = models.CharField(max_length=11)
	correo = models.EmailField()
	fumador = models.CharField(max_length=1, choices=FUMA)
	alergico = models.CharField(max_length=20)
	motivo = models.CharField(max_length=50)
	area = models.ForeignKey(Area, null=True, blank=True, on_delete=models.CASCADE)

	def __str__(self):
		return '{} {}'.format(self.nombres, self.apellidos)




		

apps/paciente/forms.py
from django import forms
from apps.paciente.models import Paciente, Area
from django.contrib.admin import widgets
import datetime
from django.forms.extras.widgets import SelectDateWidget

BIRTH_YEAR_CHOICES = ('1980', '1981', '1982')

class PacienteForm(forms.ModelForm):
	
	class Meta:
		model = Paciente
		fields = [
			'nombres',
			'apellidos',
			'cedula',
			'fecha_nacimiento',
			'edad',
			'genero',
			'tipo_sangre',
			'telefono',
			'correo',
			'fumador',
			'alergico',
			'motivo',
			'area',
			]

		labels = {
			'nombres': 'Nombres',
			'apellidos': 'Apellidos',
			'cedula': 'Cedula',
			'fecha_nacimiento': 'Fecha de Nacimiento (DD-MM-YYYY)',
			'edad': 'Edad',
			'genero': 'Genero',
			'tipo_sangre': 'Tipo de Sangre',
			'telefono': 'Telefono',
			'correo': 'Correo',
			'fumador': '¿Fumador?',
			'alergico': '¿Alergico a algún medicamento?',
			'motivo': 'Motivo de la visita',
			'area': 'Área a ser remitido',
			}

		widgets = {
			'nombres': forms.TextInput(attrs={'class':'form-control'}),
			'apellidos': forms.TextInput(attrs={'class':'form-control'}),
			'cedula': forms.TextInput(attrs={'class':'form-control'}),
			#'fecha_nacimiento': forms.DateField(widget=forms.SelectDateWidget(years=BIRTH_YEAR_CHOICES)),
			#'fecha_nacimiento': forms.DateInput(attrs={'class': 'datepicker'}, format='%d/%m/%Y'),
			#'fecha_nacimiento': forms.DateField(required=False,
        	#	widget=forms.DateInput(attrs={'class': 'datepicker'}),
        	#	help_text="Format: YYYY-MM-DD", is_hidden=False),
        	'fecha_nacimiento': forms.TextInput(attrs={'class':'form-control'}),
			'edad': forms.TextInput(attrs={'class':'form-control'}),
			'genero': forms.Select(attrs={'class':'form-control'}),
			'tipo_sangre': forms.TextInput(attrs={'class':'form-control'}),
			'telefono': forms.TextInput(attrs={'class':'form-control'}),
			'correo': forms.TextInput(attrs={'class':'form-control'}),
			'fumador': forms.Select(attrs={'class':'form-control'}),
			'alergico': forms.TextInput(attrs={'class':'form-control'}),
			'motivo': forms.TextInput(attrs={'class':'form-control'}),
			'area': forms.Select(attrs={'class':'form-control'}),	
			}

class AreaForm(forms.ModelForm):

	class Meta:
		model = Area
		fields = [
			'nombre',
			'ubicacion',
			'jefe',
			]

		labels = {
			'nombre': 'Nombre del Área',
			'ubicacion': 'Ubicación del Área',
			'jefe': 'Jefe del Área',
			}
		
		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'ubicacion': forms.TextInput(attrs={'class':'form-control'}),
			'jefe': forms.TextInput(attrs={'class':'form-control'}),
			}

apps/paciente/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from apps.paciente.forms import PacienteForm, AreaForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from apps.paciente.models import Paciente, Area

# Create your views here.

def index_paciente(request):
	return render(request, 'paciente/index_paciente.html')

def paciente_view(request):
	if request.method == 'POST':
		form = PacienteForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('paciente:paciente_listar')
	else:
		form = PacienteForm()
	return render(request, 'paciente/paciente_form.html', {'form': form})

def area_view(request):
	if request.method == 'POST':
		form = AreaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('paciente:area_listar')
	else:
		form = AreaForm()
	return render(request, 'paciente/area_form.html', {'form': form})

def paciente_list(request):
	paciente = Paciente.objects.all().order_by('id')
	contexto = {'pacientes': paciente}
	return render(request, 'paciente/paciente_list.html', contexto)

def area_list(request):
	area = Area.objects.all().order_by('id')
	contexto = {'areas': area}
	return render(request, 'paciente/area_list.html', contexto)

def paciente_edit(request, id_paciente):
	paciente = Paciente.objects.get(id=id_paciente)
	if request.method == 'GET':
		form = PacienteForm(instance=paciente)
	else:
		form = PacienteForm(request.POST, instance=paciente)
		if form.is_valid():
			form.save()
		return redirect('paciente:paciente_listar')
	return render(request, 'paciente/paciente_form.html', {'form':form})

def area_edit(request, id_area):
	area = Area.objects.get(id=id_area)
	if request.method == 'GET':
		form = AreaForm(instance=area)
	else:
		form = AreaForm(request.POST, instance=area)
		if form.is_valid():
			form.save()
		return redirect('paciente:area_listar')
	return render(request, 'paciente/area_form.html', {'form': form})

def paciente_delete(request, id_paciente):
	paciente = Paciente.objects.get(id=id_paciente)
	if request.method == 'POST':
		paciente.delete()
		return redirect('paciente:paciente_listar')
	return render(request, 'paciente/paciente_delete.html', {'paciente':paciente})

def area_delete(request, id_area):
	area = Area.objects.get(id=id_area)
	if request.method == 'POST':
		area.delete()
		return redirect('paciente:area_listar')
	return render(request, 'paciente/area_delete.html', {'area':area})

class PacienteList(ListView):
	model = Paciente
	template_name = 'paciente/paciente_list.html'
	#paginate_by = 5

class AreaList(ListView):
	model = Area
	template_name = 'paciente/area_list.html'
	#paginate_by = 5

class PacienteCreate(CreateView):
	model = Paciente
	form_class = PacienteForm
	template_name = 'paciente/paciente_form.html'
	succes_url = reverse_lazy('paciente:paciente_listar')

class AreaCreate(CreateView):
	model = Area
	form_class = AreaForm
	template_name = 'paciente/area_form.html'
	succes_url = reverse_lazy('paciente:area_listar')

class PacienteUpdate(UpdateView):
	model = Paciente
	form_class = PacienteForm
	template_name = 'paciente/paciente_form.html'
	succes_url = reverse_lazy('paciente:paciente_listar')

class AreaUpdate(UpdateView):
	model = Area
	form_class = AreaForm
	template_name = 'paciente/area_form.html'
	succes_url = reverse_lazy('paciente:area_listar')

class PacienteDelete(DeleteView):
	model = Paciente
	template_name = 'paciente/paciente_delete.html'
	succes_url = reverse_lazy('paciente:paciente_listar')

class AreaDelete(DeleteView):
	model = Area
	template_name = 'paciente/area_delete.html'
	succes_url = reverse_lazy('paciene:area_listar')

templates/paciente/area_delete.html
{% extends 'base/base.html' %}

{% block title %}

Eliminar Área

{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ area.nombre }}</h3>
	<button class="btn btn-danger" type="submit"> Sí, eliminar </button>
	<a class="btn btn-default" href="{% url 'paciente:area_listar' %}"> Cancelar </a>
</form>

{% endblock %}

templates/paciente/area_form.html
{% extends 'base/base.html' %}

{% block title %}

Registrar Área

{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit"> Guardar </button>
</form>

{% endblock %}

templates/paciente/area_list.html
{% extends 'base/base.html' %}

{% block title %}

Lista de Áreas

{% endblock %}

{% block content %}

{% if object_list %}
<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Ubicación</td>
			<td>Jefe</td>
			<td>Opciones</td>
		</tr>
	</thead>
	<tbody>
		{% if object_list %}
		{% for area in object_list %}
		<tr>
			<td>{{ area.id }}</td>
			<td>{{ area.nombre }}</td>
			<td>{{ area.ubicacion }}</td>
			<td>{{ area.jefe }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'paciente:area_editar' area.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'paciente:area_eliminar' area.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay registros de areas</h1>
		
		{% endif %}
	</tbody>
{% endif %}
</table>

{% endblock %}

templates/paciente/index_paciente.html
{% extends 'base/base.html' %}

{% block title %}
Ambulatorio Karin
{% endblock %}

{% block content %}
<h1> Bienvenido al Ambulatorio Karin, por favor inicie sesión </h1>
{% endblock %}

templates/paciente/paciente_delete.html
{% extends 'base/base.html' %}

{% block title %}

Eliminar Paciente

{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ paciente.nombres }} {{ paciente.apellidos }}</h3>
	<button class="btn btn-danger" type="submit"> Sí, eliminar </button>
	<a class="btn btn-default" href="{% url 'paciente:paciente_listar' %}"> Cancelar </a>
</form>

{% endblock %}

templates/paciente/paciente_form.html
{% extends 'base/base.html' %}

{% block title %}

Registrar Paciente

{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<!-- {{ form.as_p }} -->
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.nombres.name}}">{{form.nombres.label}}</label>
				{{form.nombres}}
			</div>
		</div>

		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.nombre.apellidos}}">{{form.apellidos.label}}</label>
				{{form.apellidos}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.cedula.name}}">{{form.cedula.label}}</label>
				{{form.cedula}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.fecha_nacimiento.name}}">{{form.fecha_nacimiento.label}}</label>
				{{form.fecha_nacimiento}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.edad.name}}">{{form.edad.label}}</label>
				{{form.edad}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.genero.name}}">{{form.genero.label}}</label>
				{{form.genero}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.tipo_sangre.name}}">{{form.tipo_sangre.label}}</label>
				{{form.tipo_sangre}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.telefono.name}}">{{form.telefono.label}}</label>
				{{form.telefono}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.correo.name}}">{{form.correo.label}}</label>
				{{form.correo}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.fumador.name}}">{{form.fumador.label}}</label>
				{{form.fumador}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.alergico.name}}">{{form.alergico.label}}</label>
				{{form.alergico}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.motivo.name}}">{{form.motivo.label}}</label>
				{{form.motivo}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.area.name}}">{{form.area.label}}</label>
				{{form.area}}
			</div>
		</div>
	</div>
	<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary" type="submit">Guardar</button>
			</div>
	</div>
</form>

{% endblock %}

templates/paciente/paciente_list.html
{% extends 'base/base.html' %}

{% block title %}

Lista de Pacientes

{% endblock %}

{% block content %}

{% if object_list %}
<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombres</td>
			<td>Apellidos</td>
			<td>Cedula</td>
			<td>Fecha de Nacimiento</td>
			<td>Edad</td>
			<td>Genero</td>
			<td>Tipo de Sangre</td>
			<td>Telefono</td>
			<td>Correo</td>
			<td>Fumador</td>
			<td>Alergico</td>
			<td>Motivo</td>
			<td>Area</td>
			<td>Opciones</td>
		</tr>
	</thead>
	<tbody>
		{% if object_list %}
		{% for paciente in object_list %}
		<tr>
			<td>{{ paciente.id }}</td>
			<td>{{ paciente.nombres }}</td>
			<td>{{ paciente.apellidos }}</td>
			<td>{{ paciente.cedula }}</td>
			<td>{{ paciente.fecha_nacimiento }}</td>
			<td>{{ paciente.edad }}</td>
			<td>{{ paciente.genero }}</td>
			<td>{{ paciente.tipo_sangre }}</td>
			<td>{{ paciente.telefono }}</td>
			<td>{{ paciente.correo }}</td>
			<td>{{ paciente.fumador }}</td>
			<td>{{ paciente.alergico }}</td>
			<td>{{ paciente.motivo }}</td>
			<td>{{ paciente.area.nombre }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'paciente:paciente_editar' paciente.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'paciente:paciente_eliminar' paciente.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay registros de pacientes</h1>
		
		{% endif %}
	</tbody>
{% endif %}
</table>

{% endblock %}