ambulatorio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, \
     password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^paciente/', include('apps.paciente.urls', namespace="paciente")),
    url(r'^medico/', include('apps.medico.urls', namespace="medico")),
    url(r'^medicamento/', include('apps.medicamento.urls', namespace="medicamento")),
    url(r'^consulta/', include('apps.consulta.urls', namespace="consulta")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/$', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^reset/password_reset/$', password_reset, 
        {'template_name':'registration/password_reset_form.html', 
        'email_template_name': 'registration/password_reset_email.html'}, name = 'password_reset'),
    url(r'^reset/password_reset_done/$', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name':'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done$', password_reset_complete, 
        {'template_name':'registration/password_reset_complete.html'}, name='password_reset_complete'),
]

apps/medicamento/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.medicamento.views import index_medicamento, medicamento_view, medicamento_list, \
	medicamento_edit, medicamento_delete, MedicamentoList, MedicamentoCreate, MedicamentoUpdate, \
	MedicamentoDelete

urlpatterns = [
	url(r'^$', login_required(index_medicamento)),
	url(r'^registrar/$', login_required(MedicamentoCreate.as_view()), name='medicamento_registrar'),
	url(r'^listar/$', login_required(MedicamentoList.as_view()), name='medicamento_listar'),
	url(r'^editar/(?P<pk>\d+)/$', login_required(MedicamentoUpdate.as_view()), name='medicamento_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$', login_required(MedicamentoDelete.as_view()), name='medicamento_eliminar'),
]

apps/medicamento/models.py
from django.db import models
# Create your models here.

class Medicamento(models.Model):
	nombre = models.CharField(max_length=20)
	presentacion = models.CharField(max_length=10)
	via = models.CharField(max_length=10)
	cantidad = models.IntegerField()
	fecha_elaboracion = models.DateField()
	fecha_vencimiento = models.DateField()	

	def __str__(self):
		return self.nombre

apps/medicamento/forms.py
from django import forms
from apps.medicamento.models import Medicamento

class MedicamentoForm(forms.ModelForm):

	class Meta:
		model = Medicamento

		fields = [
			'nombre',
			'presentacion',
			'via',
			'cantidad',
			'fecha_elaboracion',
			'fecha_vencimiento',
			]

		labels = {
			'nombre': 'Nombre',
			'presentacion': 'Presentación',
			'via': 'Vía',
			'cantidad': 'Cantidad',
			'fecha_elaboracion': 'Fecha de Elaboración (DD-MM-YYYY)',
			'fecha_vencimiento': 'Fecha de Vencimiento (DD-MM-YYYY)',
		}

		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'presentacion': forms.TextInput(attrs={'class':'form-control'}),
			'via': forms.TextInput(attrs={'class':'form-control'}),
			'cantidad': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_elaboracion': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_vencimiento': forms.TextInput(attrs={'class':'form-control'}),
		}

apps/medicamento/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from apps.medicamento.forms import MedicamentoForm
from apps.medicamento.models import Medicamento
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

# Create your views here.

def index_medicamento(request):
	return HttpResponse("Esta es la vista para la aplicacion Medicamento")

def medicamento_view(request):
	if request.method == 'POST':
		form = MedicamentoForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('medicamento:medicamento_listar')
	else:
		form = MedicamentoForm()
	return render(request, 'medicamento/medicamento_form.html', {'form': form})

def medicamento_list(request):
	medicamento = Medicamento.objects.all().order_by('id')
	contexto = {'medicamentos': medicamento}
	return render(request, 'medicamento/medicamento_list.html', contexto)

def medicamento_edit(request, id_medicamento):
	medicamento = Medicamento.objects.get(id=id_medicamento)
	if request.method == 'GET':
		form = MedicamentoForm(instance=medicamento)
	else: 
		form = MedicamentoForm(request.POST, instance=medicamento)
		if form.is_valid():
			form.save()
		return redirect('medicamento:medicamento_listar')
	return render(request, 'medicamento/medicamento_form.html', {'form': form})

def medicamento_delete(request, id_medicamento):
	medicamento = Medicamento.objects.get(id=id_medicamento)
	if request.method == 'POST':
		medicamento.delete()
		return redirect('medicamento:medicamento_listar')
	return render(request, 'medicamento/medicamento_delete.html', {'medicamento': medicamento})

class MedicamentoList(ListView):
	model = Medicamento
	template_name = 'medicamento/medicamento_list.html'
	#paginate_by = 5

class MedicamentoCreate(CreateView):
	model = Medicamento
	form_class = MedicamentoForm
	template_name = 'medicamento/medicamento_form.html'
	succes_url = reverse_lazy('medicamento:medicamento_listar')

class MedicamentoUpdate(UpdateView):
	model = Medicamento
	form_class = MedicamentoForm
	template_name = 'medicamento/medicamento_form.html'
	succes_url = reverse_lazy('medicamento:medicamento_listar')

class MedicamentoDelete(DeleteView):
	model = Medicamento
	template_name = 'medicamento/medicamento_delete.html'
	succes_url = reverse_lazy('medicamento:medicamento_listar')

templates/medicamento/medicamento_delete.html
{% extends 'base/base.html' %}

{% block title %}

Eliminar Medicamento

{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro del medicamento {{ medicamento.nombre }}</h3>
	<button class="btn btn-danger" type="submit"> Sí, eliminar </button>
	<a class="btn btn-default" href="{% url 'medicamento:medicamento_listar' %}"> Cancelar </a>
</form>

{% endblock %}

templates/medicamento/medicamento_form.html
{% extends 'base/base.html' %}

{% block title %} 

Registrar Medicamento

{% endblock %}

{% block content %}

<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit"> Guardar </button>
</form>

{% endblock %}

templates/medicamento/medicamento_list.html
{% extends 'base/base.html' %}

{% block title %}

Lista de Medicamentos

{% endblock %}

{% block content %}

{% if object_list %}
<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Presentación</td>
			<td>Vía</td>
			<td>Cantidad</td>
			<td>Fecha de Elaboración</td>
			<td>Fecha de Vencimiento</td>
			<td>Opciones</td>
		</tr>
	</thead>
	<tbody>
		{% if object_list %}
		{% for medicamento in object_list %}
		<tr>
			<td>{{ medicamento.id }}</td>
			<td>{{ medicamento.nombre }}</td>
			<td>{{ medicamento.presentacion }}</td>
			<td>{{ medicamento.via }}</td>
			<td>{{ medicamento.cantidad }}</td>
			<td>{{ medicamento.fecha_elaboracion }}</td>
			<td>{{ medicamento.fecha_vencimiento }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'medicamento:medicamento_editar' medicamento.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'medicamento:medicamento_eliminar' medicamento.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
	{% else %}
	<h1>No hay registros de Medicamentos</h1>
		
	{% endif %}
	</tbody>
{% endif %}
</table>

{% endblock %}